import dynamic from "next/dynamic";
import Head from "next/head";
import { useRouter } from "next/router";

const NavBar = dynamic(import("../components/navbar/NavBar"));
const Banner = dynamic(import("../components/banner/Banner"));
const Values = dynamic(import("../components/values/Values"));
const Convert = dynamic(import("../components/convert/Convert"));
const Features = dynamic(import("../components/features/Features"));
const Ekival = dynamic(import("../components/ekival/Ekival"));
const Team = dynamic(import("../components/team/Team"));
const Footer = dynamic(import("../components/footer/Footer"));
const Timeline = dynamic(import("../components/timeline/Timeline"));
const Partners = dynamic(import("../components/partners/Partners"));

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Ekival</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Banner />
      <Values />
      <Convert />
      <Features />
      <Ekival />
      <Timeline />
      <Partners />
      <Team />
      <Footer />
    </>
  );
}
